import type { Metadata } from "next";
import styles from "./sass/style.module.scss";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Prayer Tracker",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <div className={styles.page}>
                    <header className={styles.header}>
                        <h1>Prayer Tracker</h1>
                    </header>
                    <main className={styles.main}>{children}</main>
                    <footer className={styles.footer}>
                        <a
                            href="https://github.com/jsp220"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            GitHub
                        </a>
                        <a
                            href="https://www.linkedin.com/in/joon-park-155a7424/"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            LinkedIn
                        </a>
                        <div>©2025 Joon Park</div>
                    </footer>
                </div>
            </body>
        </html>
    );
}
